### ISSUE TITLE
New badge suggestion

### ISSUE THREAD

**Issue by QuentinFelix** [freesewing/site#100]
Patern Maker Level: Newborn

For completing the pattern drafting tutorial (Baby Bib)

Patern Maker Level: Teenage

For Making your own first pattern

Patern Maker Level: Adult

For making a pattern including several parts, evolving with measurements, and with at least one option

Patern Maker Level: Senior 

For having a pattern beeing used by another maker.

**Comment by joostdecock** [comment]
😊 so you want to be a newborn?

I'll see when I can find time to add something like this

**Comment by QuentinFelix** [comment]
Haha, for now =)

**Comment by QuentinFelix** [comment]
How do I get the draft, fork and ambassador badges btw?

**Comment by joostdecock** [comment]
You're supposed to get it for drafting a pattern. But you don't seem to have it so perhaps there's a bug somewhere and nobody ever gets it.

I'll look in to it.

**Comment by joostdecock** [comment]
You get the ambassador badge for spreading the word about freesewing. Basically,talking about freesewing in a blog post or on social media or something.

This is obviously not automatic, so I need to know about it ;)

**Comment by joostdecock** [comment]
No, that draft badge seems to work as expected.

**Comment by joostdecock** [comment]
I've added the designer-apprentice badge (and you've got it).
I'll close this for now, we can add more badges as we move along ;)

**Comment by QuentinFelix** [comment]
I like this badge system =)
Ambassador badge: what about my posts on instagram? (Not that, at that time, I did it for that purpose) https://www.instagram.com/p/BZTQ4r3hmNd/?taken-by=felixquentin https://www.instagram.com/p/BYS4r4mB0Z_/?taken-by=felixquentin https://www.instagram.com/p/BYUER9GhcZt/?taken-by=felixquentin

Draft: I just made one (the previous ones I made were on makemypattern and it seems like drafts were not part of the migration), but the badge is not there yet.

Nice designer-apprentice badge =)

**Comment by joostdecock** [comment]
Yes, that would do it 😊 As I said, it's not automatic so it's good you pointed it out. 

I've updated your badges, including the draft badge
