### ISSUE TITLE
Button free length is off by 2cm, and top button placement needs work

### ISSUE THREAD

**Issue by Stefan1960** [freesewing/site#112]
See [here](https://freesewing.org/drafts/ayecz)
Hi Joost,
here comes a minor issue with button positions, but probably worth for correction:
a) "button free length" implies a zero line being the waist line. However, when set to zero the lowest button is 2cm above the waist line. Whatever value is chosen, the lowest button is wrong by said 2cm. Makes exakt positioning difficult.
b) topmost button is too low, in particular when not opting for the extra top button. The top button is positioned below the top edge by a distance being equal to the regular button-to-button-distance. This leads to a total distance "top button" <=> "central collar button" being even higher by half of the collar stand height, which is too much. Maximum should be "top button" <=> "central collar button" equal to regular button-to-button-distance. However, when having a closer look at off-the-shelf shirts, this top distance is always even shorter. So maybe it's wise to include an option for adjusting this top distance.

Good night, need a sleep now,
Stefan

**Comment by joostdecock** [comment]
Thank you for reporting this Stefan. I am dealing with some low-level issues for the moment, and will pick this up as soon as I can

**Comment by woutervdub** [comment]
I'll work on this.

**Comment by joostdecock** [comment]
I've merged a fix for this into the core develop branch.
Top button is now closer to the collar button. If there's an extra top button, it goes between the top and second button on the shirt.

**Comment by Stefan1960** [comment]
Looks good now. Thank you two for working on this and resolving both issues.
Freesewing is great thanks to people like you.

Stefan
