### ISSUE TITLE
huey armholeDepthFactor option is undocumented

### ISSUE THREAD

**Issue by TenderChunx** [freesewing/site#150]
The armholeDepthFactor option of the huey pattern is undocumented.

Feel free to include comments, but please keep the line above intact.

**Comment by joostdecock** [comment]
Hmm, I'm very interested to hear how you stumbled upon this.  It had the formatting of our *Please report this* messages on the site, but the option [is documented](https://freesewing.org/docs/patterns/huey/options#armholeDepthFactor).

Would you be able to clarify?

Tx

**Comment by TenderChunx** [comment]
Not really sure, I did find that it was documented, my Connection might have slipt…
But unless that’s the reason, I have no clue!

😉

Fra: Joost<mailto:notifications@github.com>
Sendt: onsdag 25. oktober 2017 kl. 17:37
Til: freesewing/site<mailto:site@noreply.github.com>
Kopi: TenderChunx<mailto:unequal@outlook.com>; Author<mailto:author@noreply.github.com>
Emne: Re: [freesewing/site] huey armholeDepthFactor option is undocumented (#150)


Hmm, I'm very interested to hear how you stumbled upon this. It had the formatting of our Please report this messages on the site, but the option is documented<https://freesewing.org/docs/patterns/huey/options#armholeDepthFactor>.

Would you be able to clarify?

Tx

**Comment by joostdecock** [comment]
I'll have a look into it tomorrow 😉
