### ISSUE TITLE
Social media accounts

### ISSUE THREAD

**Issue by woutervdub** [freesewing/site#184]
Add options for people to add social media account information to their profile/account

**Comment by joostdecock** [comment]
So this perhaps needs no explaining, but I really think it's important to protect people's privacy, and prevent online tracking.

So I will add this, but will only use it to add links to the social media accounts to the profile page, and comments and so on.

I will not add some sort of integration with these services that would require us to run their javascript code, nor will I contact their APIs. 

Deal?

**Comment by woutervdub** [comment]
Oh yeah, I definitely don't want their code to be run on the freesewing site. I just thought it would be nice to allow people to publish their handle if they want to. You're already doing that with the `Showcase`, I believe. No integration of any sorts with those social media platforms is my preference. Let's keep this free and independent.

**Comment by joostdecock** [comment]
It is done :)
