### ISSUE TITLE
Failed to draft simon for model pevda

### ISSUE THREAD

**Issue by ronny19jenny** [freesewing/site#194]
These links should recreate the issue:

 - [On core master branch](https://core.freesewing.org/?service=draft&acrossBack=20&bicepsCircumference=13.5&centerBackNeckToWaist=22&chestCircumference=43.5&hipsCircumference=44&naturalWaist=43.5&naturalWaistToHip=10&neckCircumference=17.5&shoulderToElbow=13&shoulderToShoulder=19&shoulderToWrist=24&wristCircumference=7.5&shoulderSlope=13&seamAllowance=imperial&customSa=0.625&scope=all&theme=Basic&lang=en&chestEase=6.25&waistEase=6.25&hipsEase=6.25&bicepsEase=1.625&collarEase=0.625&cuffEase=1.375&lengthBonus=5.875&sleeveLengthBonus=1.625&yokeDart=0.25&hipFlare=0.375&buttonfreeLength=0.375&hemStyle=1&hemCurve=3.125&buttons=7&extraTopButton=1&splitYoke=0&buttonPlacketType=1&buttonPlacketStyle=1&buttonPlacketWidth=0.75&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=1.375&buttonholePlacketFoldWidth=0.25&sleevePlacketWidth=1&sleevePlacketLength=7.125&collarStandWidth=1.375&collarStandBend=0.25&collarStandCurve=0.25&collarGap=1&collarBend=0.625&collarFlare=0.375&collarAngle=85&collarRoll=0.25&cuffStyle=2&cuffLength=2.5&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=1.625&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.25&sa=0.625&userUnits=imperial&fork=true&pattern=SimonShirt&model=pevda&defaultMetricSa=1&defaultImperialSa=0.625)
 - [On core develop branch](https://dev.core.freesewing.org/?service=draft&acrossBack=20&bicepsCircumference=13.5&centerBackNeckToWaist=22&chestCircumference=43.5&hipsCircumference=44&naturalWaist=43.5&naturalWaistToHip=10&neckCircumference=17.5&shoulderToElbow=13&shoulderToShoulder=19&shoulderToWrist=24&wristCircumference=7.5&shoulderSlope=13&seamAllowance=imperial&customSa=0.625&scope=all&theme=Basic&lang=en&chestEase=6.25&waistEase=6.25&hipsEase=6.25&bicepsEase=1.625&collarEase=0.625&cuffEase=1.375&lengthBonus=5.875&sleeveLengthBonus=1.625&yokeDart=0.25&hipFlare=0.375&buttonfreeLength=0.375&hemStyle=1&hemCurve=3.125&buttons=7&extraTopButton=1&splitYoke=0&buttonPlacketType=1&buttonPlacketStyle=1&buttonPlacketWidth=0.75&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=1.375&buttonholePlacketFoldWidth=0.25&sleevePlacketWidth=1&sleevePlacketLength=7.125&collarStandWidth=1.375&collarStandBend=0.25&collarStandCurve=0.25&collarGap=1&collarBend=0.625&collarFlare=0.375&collarAngle=85&collarRoll=0.25&cuffStyle=2&cuffLength=2.5&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=1.625&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.25&sa=0.625&userUnits=imperial&fork=true&pattern=SimonShirt&model=pevda&defaultMetricSa=1&defaultImperialSa=0.625)
 - [On core bleeding edge](https://joost.core.freesewing.org/?service=draft&acrossBack=20&bicepsCircumference=13.5&centerBackNeckToWaist=22&chestCircumference=43.5&hipsCircumference=44&naturalWaist=43.5&naturalWaistToHip=10&neckCircumference=17.5&shoulderToElbow=13&shoulderToShoulder=19&shoulderToWrist=24&wristCircumference=7.5&shoulderSlope=13&seamAllowance=imperial&customSa=0.625&scope=all&theme=Basic&lang=en&chestEase=6.25&waistEase=6.25&hipsEase=6.25&bicepsEase=1.625&collarEase=0.625&cuffEase=1.375&lengthBonus=5.875&sleeveLengthBonus=1.625&yokeDart=0.25&hipFlare=0.375&buttonfreeLength=0.375&hemStyle=1&hemCurve=3.125&buttons=7&extraTopButton=1&splitYoke=0&buttonPlacketType=1&buttonPlacketStyle=1&buttonPlacketWidth=0.75&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=1.375&buttonholePlacketFoldWidth=0.25&sleevePlacketWidth=1&sleevePlacketLength=7.125&collarStandWidth=1.375&collarStandBend=0.25&collarStandCurve=0.25&collarGap=1&collarBend=0.625&collarFlare=0.375&collarAngle=85&collarRoll=0.25&cuffStyle=2&cuffLength=2.5&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=1.625&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.25&sa=0.625&userUnits=imperial&fork=true&pattern=SimonShirt&model=pevda&defaultMetricSa=1&defaultImperialSa=0.625)

## Please keep the info above intact
You can include further info and comments here

**Comment by joostdecock** [comment]
Dear @ronny19jenny 

Please double-check the **Shoulder slope** measurments. Your model has it listed as 19 inch, which is not possible. For comparison, my shoulder slope measurement is just over 2 inch.

Please check [the documentation on how to measure your shoulder slope](https://freesewing.org/docs/measurements/shoulderslope) and update your model data.

If the problem persists after that, feel free to create a new issue.

**Comment by ronny19jenny** [comment]
Thank You! That makes sense now!
