### ISSUE TITLE
Draft reference link

### ISSUE THREAD

**Issue by woutervdub** [freesewing/site#203]
## Your drafts

The draft reference link under **Details**, **Info** is not refreshed correctly when switching from `share` `No` to `Yes`. 

Also, when switching this `Setting` back and forth without refreshing the page, the references get added on top of each other.

**Comment by joostdecock** [comment]
I gave you that bug badge for this 😉

You assigned this to yourself. Are you planning to submit a pull request? Or was that not what you meant?

**Comment by woutervdub** [comment]
Already done. :-)
And thanks!
    On Thursday, November 30, 2017, 9:35:44 AM PST, Joost <notifications@github.com> wrote:  
 
 
I gave you that bug badge for this 😉
 
You assigned this to yourself. Are you planning to submit a pull request? Or was that not what you meant?
