### ISSUE TITLE
Failed to draft theo for model dnqah

### ISSUE THREAD

**Issue by Maxwellamankwaa** [freesewing/site#244]
These links should recreate the issue:

 - [On core master branch](https://core.freesewing.org/?service=draft&hipsCircumference=31&inseam=27&seatCircumference=37&seatDepth=8&seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=4&backRise=4&lengthBonus=2&sa=1&userUnits=metric&fork=true&pattern=TheoTrousers&model=dnqah&defaultMetricSa=1&defaultImperialSa=0.625)
 - [On core develop branch](https://dev.core.freesewing.org/?service=draft&hipsCircumference=31&inseam=27&seatCircumference=37&seatDepth=8&seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=4&backRise=4&lengthBonus=2&sa=1&userUnits=metric&fork=true&pattern=TheoTrousers&model=dnqah&defaultMetricSa=1&defaultImperialSa=0.625)
 - [On core bleeding edge](https://joost.core.freesewing.org/?service=draft&hipsCircumference=31&inseam=27&seatCircumference=37&seatDepth=8&seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=4&backRise=4&lengthBonus=2&sa=1&userUnits=metric&fork=true&pattern=TheoTrousers&model=dnqah&defaultMetricSa=1&defaultImperialSa=0.625)

## Please keep the info above intact
You can include further info and comments here

**Comment by joostdecock** [comment]
I seem to have missed this issue somehow. I'm sorry and will look into this now.

**Comment by joostdecock** [comment]
You specified your model measurements in inches ( eg: seat circumference is 27) however, your model is configured as having metric settings.

First of all, double-check your account settings. Go to https://freesewing.org/welcome and follow the steps.

Then, update the settings for this model specifically. Go to https://freesewing.org/models/dnqah click **Settings** and set the units to **Imperial**

Then, try again.
