### ISSUE TITLE
Failed to draft theodore for model dnqah

### ISSUE THREAD

**Issue by Maxwellamankwaa** [freesewing/site#246]
These links should recreate the issue:

 - [On core master branch](https://core.freesewing.org/?service=draft&hipsCircumference=31&inseam=27&seatCircumference=37&seatDepth=8&seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=5&backRise=4&lengthBonus=4&sa=1&userUnits=metric&fork=true&pattern=TheodoreTrousers&model=dnqah&defaultMetricSa=1&defaultImperialSa=0.625)
 - [On core develop branch](https://dev.core.freesewing.org/?service=draft&hipsCircumference=31&inseam=27&seatCircumference=37&seatDepth=8&seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=5&backRise=4&lengthBonus=4&sa=1&userUnits=metric&fork=true&pattern=TheodoreTrousers&model=dnqah&defaultMetricSa=1&defaultImperialSa=0.625)
 - [On core bleeding edge](https://joost.core.freesewing.org/?service=draft&hipsCircumference=31&inseam=27&seatCircumference=37&seatDepth=8&seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&waistbandWidth=5&backRise=4&lengthBonus=4&sa=1&userUnits=metric&fork=true&pattern=TheodoreTrousers&model=dnqah&defaultMetricSa=1&defaultImperialSa=0.625)

## Please keep the info above intact
You can include further info and comments here

**Comment by joostdecock** [comment]
Your account and model has their units set to metric, but the measurements you entered are clearly meant as imperial.

Go to your profile, set your units to imperial.
Then, do the same in your model settings.
Then, redraft this pattern.
