### ISSUE TITLE
Standard metric seam allowance (1 cm) setting = 1 inch when set to imperial 

### ISSUE THREAD

**Issue by nutation** [freesewing/site#292]
When selecting "Standard metric seam allowance (1 cm)" on the Simon shirt pattern it generates with 1  inch seam allowances.

**Comment by joostdecock** [comment]
Sorry for the delay. I've implemented a fix for this, it will be rolled out to the site later today.

**Comment by joostdecock** [comment]
The fix has been deployed

**Comment by nutation** [comment]
Awesome!! I am really loving all your hard work, just learning to sew but I have worked in Silicon Valley my whole life and this was exactly what I was looking for
