### ISSUE TITLE
Problem with draft pnfcq

### ISSUE THREAD

**Issue by bryanksokol** [freesewing/site#310]
See [here](https://freesewing.org/drafts/pnfcq)
My draft is WAY off with the comparison.  I measured using metric but you can see that.  What is the matter?

**Comment by joostdecock** [comment]
Unless you're a child, those measurements can't be correct.

The most likely explanation is that you entered imperial measurements as metric, which will cause the to be off by a factor of 2.54.

If you're used to imperial, switch your account and model to imperial. Adapt your measurements, and you should be fine.

I'll keep this open pending your feedback

**Comment by bryanksokol** [comment]
So, I figured that was it, but I have them set as metric and put in
metric.  I think they're correct,zip too.  Regardless Ill do them over as
imperial and see what results.
Thanks, Joost!

**Comment by joostdecock** [comment]
I noticed that you've updated the measurements and things look fine now.
So I'm closing this :)
