### ISSUE TITLE
Problem with draft awnps

### ISSUE THREAD

**Issue by SJKurtz** [freesewing/site#40]
See [here](dev.freesewing.org/drafts/awnps)
EVen better. Problem seems to be that my account SEEMS to be sending me back to metric as a default between drafts. And I reset to imperial. I'll just keep smacking this until I get the same results twice in a row

**Comment by joostdecock** [comment]
This draft isn't shared, so I can't see it. 
Which makes me think that maybe I should set a draft to shared auto-magically if people report it as broken. Might be a nice feature.

**Comment by joostdecock** [comment]
Ok, I shared your draft my messing around in the database.
This one looks way better :) although I'm concerned your shoulder to shoulder measurement makes no sense with that across back measurement

**Comment by joostdecock** [comment]
I've rolled out a bunch of updates for imperial (see https://github.com/freesewing/site/issues/31 )

As such, this is outdated and I'm going to close this. Please try to reproduce this and open a new issue if you can.

**Comment by SJKurtz** [comment]
I am a chubby 58 year old woman. It makes perfect sense to me 😉

I am going over these again this week, starting from scratch. And while I believe that mismatch is mostly correct, it’s probably not that great, so I will hire one of my kids to get a precise measurement.

Stephanie

**Comment by joostdecock** [comment]
You're a 58 year old woman who's helping track down bugs in an open source software project.

That's pretty badass :1st_place_medal:
