### ISSUE TITLE
Screen formatting on paperless drafts pages-downloads overlay draft

### ISSUE THREAD

**Issue by Katesfolly** [freesewing/site#44]
When viewing the paperless draft of either Aaron or Simon, I experienced the download buttons laying over the draft.  This adjusted when I resized the window (though I had to go to some odd proportions to get it to look right).  This occurred in both firefox for Windows and Safari for Mac. 

(As an aside, I also have access to Firefox for Mac and IE and Chrome for windows if you ever want me to test something in multiple browsers.)

![screen shot 2017-07-19 at 9 37 04 pm](https://user-images.githubusercontent.com/30324809/28480573-ea2931ec-6e26-11e7-9447-9238e40d15fc.png)

**Comment by joostdecock** [comment]
The image is an SVG injected into the DOM. It is supposed to adapt to the available space (in other words, be responsive) but obviously that doesn't always seem to work.

I'll try to find a browser combo where I can reproduce this, and then come up with a fix.
What this space.

**Comment by joostdecock** [comment]
I've changed the way the SVG is included in the page.
Could you please check from your side whether this fixes the issue?

**Comment by Katesfolly** [comment]
Joost, yep, on paperless drafts, everything lays out in the browser window
beautifully!  (at least on Safari and Firefox for Mac)

**Comment by joostdecock** [comment]
:smiley: I love it when a plan comes together.

Ok, closing. Thanks for the feedback.
