### ISSUE TITLE
Problem with draft xwaef

### ISSUE THREAD

**Issue by ohbearcgn** [freesewing/site#47]
See [here](https://dev.freesewing.org/drafts/xwaef)

Hm, wie ein Tanktop sieht das jetzt nicht aus. Wo hab ich was falsch gemacht?

**Comment by joostdecock** [comment]
I broke the stretch option today. Sorry about that. I will fix it tomorrow.

**Comment by joostdecock** [comment]
Ok, I fixed it in [the latest update to core](https://github.com/freesewing/core/commit/62be909c7723c75bf518d53d436475b5ef3c5939).
Sorry about that. It will take a few minutes before Travis deploys the latest update. 
But once it does, you can simply redraft your draft, and it should be fine.

Thanks in advance for confirming that it's fixed so I can close this issue.
And thanks for reporting it 👍

**Comment by joostdecock** [comment]
Just forked it, and it's fine. So the update is deployed.

Let me know whether it works for you.

**Comment by ohbearcgn** [comment]
Jetzt sieht's gut aus. :-)

Liebe Grüsse Stefan 

brummm

**Comment by joostdecock** [comment]
Tx :)
