### ISSUE TITLE
theo configuration options are not documented

### ISSUE THREAD

**Issue by jdeantoni** [freesewing/site#51]
Hi,

trying to understand the "general option" of the theo pattern I have a page telling me the documentation is missing:

> This documentation is missing
> We don't seem to have documentation for the presetSa option. That shouldn't happen, so I encourage you to report this.

thanks for the great job !

**Comment by joostdecock** [comment]
Thanks for reporting this. All pattern options under *general* are still to be documented (see also #49)

I hope to add this later today

**Comment by joostdecock** [comment]
This has been added/fixed
