### ISSUE TITLE
brian chestEase option is undocumented

### ISSUE THREAD

**Issue by mo77019** [freesewing/site#59]
The chestEase option in group fit of the  pattern (aka brian) is undocumented.

missing doc for:
Home » Docs » Pattern docs » Brian » Brian options » chest ease

**Comment by joostdecock** [comment]
Thank you for reporting this, I've fixed it.
If you can let me know your username on the site, I will assign you the **issue** badge, you've earned it 👍

**Comment by mo77019** [comment]
Sure.    I'm Mark; initially was user 170 on freesewing.  

(and mo77019 on reddit if you couldn't guess that from this new Reddit github acct.)

**Comment by joostdecock** [comment]
Ah, I didn't put 2 and 2 together ☺️
Thanks Mark, you have a brew badge now: https://freesewing.org/users/yknzt

**Comment by joostdecock** [comment]
New, not brew
