### ISSUE TITLE
Enhancement: Allow printing from web pages

### ISSUE THREAD

**Issue by mo77019** [freesewing/site#65]
Currently, printing from the Model Details (https://freesewing.org/models/XXXXX) and Draft Details page (e.g. https://freesewing.org/drafts/XXXXX) is disallowed with a message not to print web pages.

I'm trying to print these pages, so I have a record of the measurements used, ease and fit options, (as I'm noticing some inconsistencies in my drafted HUGO pattern.)  I'd print my Model pages to PDF to save in case there is a problem and they're lost.

Recommend: Let the users print site-wide, even if it doesn't make sense.

**Comment by joostdecock** [comment]
I've changed the print styles so you can now print content. Give it a few minutes before it's deployed to the production site.
