### ISSUE TITLE
Hello...I'm sorry but there seems to be a problem...I can't get any documentation whatsoever on your magnificient site...I tried Simon documentation: doesn"t work. And...it seems no other documentation works. :'( I hope it is just a matter of fixing the site? i love what you're doing. Thank you very much. Marie

### ISSUE THREAD

**Issue by mariraf** [freesewing/site#657]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by mariraf** [comment]
Hello...I'm sorry but there seems to be a problem...I can't get any documentation whatsoever on your magnificient site...I tried Simon documentation: doesn"t work. And...it seems no other documentation works either. :'( I hope it is just a matter of fixing the site? i love what you're doing. Thank you very much. Marie

**Comment by joostdecock** [comment]
Our latest update has indeed broken a few things. We're working on it and hope to have everything back to normal soon.

In the meanwhile, you can read the documentation on our beta site: https://beta.freesewing.org/en/docs/patterns/simon

**Comment by joostdecock** [comment]
I've rolled back an earlier version while we figure out what's causing the problem.
Things should work again :)

**Comment by mariraf** [comment]
Oh thank you sooo much!!!!!!!! You are so..so...so...incredible! So kind and dedicated!!!! <3 +++
