### ISSUE TITLE
Theodore failed to generate. 

### ISSUE THREAD

**Issue by GitBen2** [freesewing/site#659]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
Do you have a draft reference for this? If not, your freesewing username and the model you drafted this for.

tx

**Comment by joostdecock** [comment]
Stale: closing
