### ISSUE TITLE
all patterns are failing to draft

### ISSUE THREAD

**Issue by GitBen2** [freesewing/site#660]
Thanks for reporting an issue. Please keep in mind that:

 - Problems with patterns are for the [core](https://github.com/freesewing/core/issues/new) repository
 - Website issues are for the [site](https://github.com/freesewing/site/issues/new) repository
 - Problems with the data backend are for the [data](https://github.com/freesewing/data/issues/new) repository

**Comment by joostdecock** [comment]
Thank you for reporting thing. An SSL certificate on one of our backends expired.
It's been updated, and everything's back to normal.
