### ISSUE TITLE
Design tutorial part 1

### ISSUE THREAD

**Issue by woutervdub** [freesewing/site#84]
Found some issues in the "Design tutorial part 1" (/docs/designer/tutorial/part-1)

All images point to something on api.freesewing.com, but that name cannot be resolved.
(part 2 too)

Under https://freesewing.org/docs/designer/tutorial/part-1#calculating-curve-length-with-partcurvelen
_Now, we want that opening to be 80% of the head circumference. So we’re going to draw it, then measure it, and tweak it until we’re **happen**._
Should be: **happy**

Under https://freesewing.org/docs/designer/tutorial/part-1#mirroring-points
_In the second part, we’re calling it **4** times with prefix top, creating points top1 to **top4**._
Should be: _In the second part, we’re calling it **5** times with prefix top, creating points top1 to **top5**._

Title of https://freesewing.org/docs/designer/tutorial/part-1#drawing-the-neck-openining
_Drawing the neck **openining**_
Should be: _Drawing the neck **opening**_

Under https://freesewing.org/docs/designer/tutorial/part-1#designing-the-bib-shape
_With our neck opening good to go, it’s time we **drew** a bib around it._
Should be: _With our neck opening good to go, it’s time we **draw** a bib around it._

**Comment by joostdecock** [comment]
Thanks for reporting this @woutervdub My latest commit fixes all these issues.

**Comment by joostdecock** [comment]
I've updated the badges in [your profile](https://freesewing.org/users/xdpug), thanks again :)
