### ISSUE TITLE
Problem with draft hrtnk

### ISSUE THREAD

**Issue by Stefan1960** [freesewing/site#87]
See [here](https://freesewing.org/drafts/hrtnk)
Hi there, I'm trying to catch up with migration from mmp to fso. Simon shirt adaption to my previous and quite well working singular shirt pattern is in progress but not yet completed.

By now I'm stumbling over adaption of Simon shirt hips ease, which seems to not work. Any alteration of ease value does not have visible impact on the drafted pattern. What's wrong?

Stefan

**Comment by joostdecock** [comment]
Hi Stefan, thanks for reporting this. [The sampler confirms](https://core.freesewing.org/?service=sample&pattern=SimonShirt&mode=options&option=hipsEase) the issue.

As soon as I get to a laptop and internet connection, I'll have a look at what's going on.

**Comment by joostdecock** [comment]
Thanks for reporting this @Stefan1960 This is now fixed, as you can see in the sampler link above.

**Comment by Stefan1960** [comment]
Yeah, it works. Thanks a lot Joost for this quick fix.
Stefan

**Comment by joostdecock** [comment]
Thanks for reporting it. I've added the issue and bug badges to [your profile](https://freesewing.org/users/kczrw) :)
